REPLACE INTO `item_db2_re` VALUES (25297,'Frozen_Stone_Fragment','Frozen Stone Fragment',3,NULL,345,10,NULL,NULL,NULL,NULL,0xFFFFFFFF,63,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `item_db2_re` VALUES (25298,'Spirit_Jewel','Spirit Jewel',3,NULL,294,10,NULL,NULL,NULL,NULL,0xFFFFFFFF,63,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `item_db2_re` VALUES (25299,'Snowball','Snowball',3,NULL,278,10,NULL,NULL,NULL,NULL,0xFFFFFFFF,63,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `item_db2_re` VALUES (25300,'Ktullanux_Eye','Ktullanux Eye',3,NULL,NULL,0,NULL,NULL,NULL,NULL,0xFFFFFFFF,63,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `item_db2_re` VALUES (25309,'Dry_Twigs','Dry Twigs',3,NULL,NULL,0,NULL,NULL,NULL,NULL,0xFFFFFFFF,63,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
